python run.py \
    --task_name SST-2 \
    --data_dir data/k-shot/SST-2/16-42 \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --do_predict \
    --evaluation_strategy steps \
    --model_name_or_path roberta-large \
    --use_prompt \
    --prompt_num 5 \
    --num_k 16 \
    --max_steps 1000 \
    --per_device_train_batch_size 2 \
    --learning_rate 2.5e-2 \
    --num_train_epochs 0 \
    --output_dir result/tmp \
    --seed 42 \
    --template "*cls**sent_0*prompt*mask*.*sep+*" \
    --mapping "{'0':'terrible','1':'great'}" \
    --num_sample 16